#
# Please do not make any changes in this file. If you want to customize
# your zsh environment, make all personal modifications in a file
# named "$HOME/.personal.zshrc". This file is "sourced" after executing
# the global.zshrc startup script.
#

STARTUP=/app

file=$STARTUP/.zshrc

if test -r $file ; then
  . $file
fi

